### ISSUE TITLE
View the input parameters used to create a layer

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#1]
Would be useful to be able to see what input parameters were used to generate an output layer. 
For example, for a Quick Time Map layer, being able to see what the method of transport, time, leaving/arriving, leave/arrive time, and start location. 
Would be particularly useful when generating multiple layers at once in a batch process.

**Comment by olivierdalang** [comment]
@Chris-Hutch-iGeo I see two ways this could be done :
A/ store the parameters in the results table (we could store the parameters as sent to the API, which could be different for each search if an expression was used)
B/ store the parameters in the layer's metadata (you'd get the parameters as inputs to the algorithms, which could be helpful if you want to run the same algorithms again)

A/ would make the output data quite a bit more complex with many columns, if we want it this way, I'd suggest to make it optional (add a checkbox labelled "includes parameters in output")

Support for B/ would vary depending on the provider to which the layer is saved, e.g. as far as I know, it's currently not possible to save metadata to databases (postgis, geopackage, ...). I think however it's possible to save it in the QGIS project in all cases.

It is also possible to do both A/ and B/.

**Comment by Chris-Hutch-iGeo** [comment]
@olivierdalang thanks for this. Do you have a sense of how much work it would be to implement either of these changes? Is one going to be significantly easier than the other?

They both sound like sensible options, and doing both might be the best approach. My gut feel is that A/ might be the better one to start with though, with the checkbox as you suggest

**Comment by olivierdalang** [comment]
A/ would be significantly easier than B/ as it doesn't require to deal with storing anything in metadata.

**Comment by Chris-Hutch-iGeo** [comment]
Ok great, think it probably makes sense to start with just A/ then and see how it looks after that

**Comment by olivierdalang** [comment]
done (in master)

I went for B/ finally, as it's cleaner and was relatively easy in the end. It relies on QGIS's metadata feature, so metadata is stored in the project by default. That's not as good as storing it in/alongside the actual data, but unfortunately there's currently no clean way to this this that would work with all data types.
