### ISSUE TITLE
Retain the metadata of a point layer in the output of the Time Map tool

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#13]
When running the Time Map tool (Simple or Advanced) it would be useful if the metadata of the input layer could be retained in the output layer (perhaps as an optional functionality).

For example, using a list of offices as the input layer, this would enable the office name and street address, for example, to be retained in the attributes of each corresponding isochrone, to make them more easily identifiable.

**Comment by olivierdalang** [comment]
Done.

I also started some work (in another branch) to generalize this to the two other algorithms, then realized it's already the case for TimeFilter. Now we can choose :
1. either keep it like this (feature only available for TimeMap, as per this issue)
2. or add the exact same parameters (including choice of which fields to keep) to the two other algorithms, which is good for consistency, but would slightly break backwards compatibility (columns would now be prefixed, to avoid clashes with fields like `id`)

@Chris-Hutch-iGeo Please reopen this issue if you want to go for 2.
