### ISSUE TITLE
Add option to include the metadata for input points when creating isochrones

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#14]
When using any of the Time Map toolbox tools to create isochrones, it would be great to have the option to include the metadata of the input points in the output data of the isochrones.

For example, if the point layer included a field for 'office name', this would be included in the output data, so when opening the attribute table of the isochrone layer you could see it.

Maybe a tick box of 'Include metadata in results' could work?

**Comment by olivierdalang** [comment]
This is the same as #13, right ?
