### ISSUE TITLE
Odd results when running Time Map for a layer of more than 10 points, using Union or Intersection

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#16]
When running the Time Map (Simple or Advanced) tool on a layer with more than 10 points, the Union and Intersection output types return a strange result. 

Looks like it displays the union or intersection of each API call separately, rather than combining them into one overall shape.

**Comment by olivierdalang** [comment]
Yes, it happens exactly as you say, as union/intersection is computed by the API.

I see two possible solutions :
- A. better document this limitation, and explain how to do it manually in two steps using normal QGIS algorithms. Would you prefer the algorithm to fail in such cases ?
- B. implement client-side intersection/union (for consistency, we'd use it also for less than 10 points datasets).

Let me know which one you prefer.

**Comment by Chris-Hutch-iGeo** [comment]
Can we go with B please, thanks
