### ISSUE TITLE
Adjust the input parameters for a layer without creating a new layer

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#2]
Would be useful to be able to adjust the input parameters for a TTP layer, without having to create a new layer.
For example, for a Quick Time Filter layer, changing the method of transport. 
This would make it easier to do more dynamic analysis in an easier way.

**Comment by olivierdalang** [comment]
See #1 as we need to store the parameters somehow to implement this

**Comment by olivierdalang** [comment]
done (in master)
