### ISSUE TITLE
Way to keep fields when using the TimeMap Advanced tool in the Graphical Modeller

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#23]
When running the TimeMap Advanced tool as normal there is the option to select the fields to keep from the input data, by clicking the three dots:

![image](https://user-images.githubusercontent.com/51789195/79332206-4e6c1100-7f14-11ea-88e1-8bebc920df31.png)

But when running the TimeMap Advanced tool in the Graphical Modeller these three dots are not there, so it's not possible to select the fields to keep:

![image](https://user-images.githubusercontent.com/51789195/79332268-70659380-7f14-11ea-88bb-c22a8a79936b.png)

Is there a way to get around this?

**Comment by olivierdalang** [comment]
When building an model, it's not known in advance the fields of the input layer (as the input layer usually is a variable). I don't think it's possible to hard-code these values ?

It is however possible to have a picker for the layers by adding a "vector field" input that accepts multiple values. Then use this input as value for the fields_to_keep fields. This way it works exactly in the same way than when running the tools as normal.

I close this issue, please feel free to reopen if this is not what you expected (but note this behaviour comes from QGIS, so any change to this would have to be done upstream in QGIS itself).
