### ISSUE TITLE
Enable locations to be entered manually when using the Quick tools

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#3]
Would be useful to be able to enter a location manually when using any of the Quick tools in the TTP toolbar.
For example, when using the Quick time map tool, you could enter the start location as an address (e.g postcode) instead of clicking a start point on the map.
This would be particularly useful when working with a map/area you are unfamiliar with (e.g you have a hotel address that you want to map some routes from, but don't know exactly where to find it on the map).

**Comment by olivierdalang** [comment]
done through the "geoclick tool" (in master)
