### ISSUE TITLE
Display the output routes from the Route tool broken down into each end-to-end route 

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#7]
There are currently two options for the Output style of the Route tool (Advanced or Simplified): 

NORMAL returns a breakdown of the routes by buckets of route times (e.g 0-5min)
ADVANCED returns a breakdown of the routes by transport type (e.g bus)

Would be useful to be able to output these routes broken down into the individual end-to-end routes as well. 

Could rename NORMAL with "By Travel Time", ADVANCED with "By Transport Type", and call the new Output style "By Route".

**Comment by olivierdalang** [comment]
done (in master)
