### ISSUE TITLE
install from zip fails

### ISSUE THREAD

**Issue by riccardoklinger** [igeolise/traveltime-platform-qgis-plugin#9]
I've donwloaded the plugin from your website and run a quite uncommon installed version as I have no admin rights on this computer. Yet I can install plugins normally, I do get an error with yours:
TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "O:/t/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "D:/Users/rklinger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\travel_time_platform_plugin\__init__.py", line 4, in classFactory
    return Main(iface)
  File "D:/Users/rklinger/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\travel_time_platform_plugin\main.py", line 47, in __init__
    locale = QSettings().value("locale/userLocale")[0:2]
TypeError: 'QVariant' object is not subscriptable

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.4.10-Madeira Madeira, 3d97aaae88

**Comment by riccardoklinger** [comment]
Install from official repo fails as well. checked in version 1.0.0 and 1.0.1. 
calling QSettings().value("locale/userLocale") reveals: NULL

**Comment by riccardoklinger** [comment]
after setting my user-GUI translation / locale in the QGIS-GUI it worked well. Maybe add a remark in the documentation.
![grafik](https://user-images.githubusercontent.com/7377897/63586508-b9419400-c5a1-11e9-8809-317cfd2a966c.png)

**Comment by olivierdalang** [comment]
Thanks for the report and investigation. I reopen as the issue is still valid and will work on a fix.
